apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: mariadb
        image: mariadb:12.2
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: mariadb-root-password
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: mariadb-database
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: mariadb-user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webserver-secrets
              key: mariadb-password
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn